version: 0.2

phases:
    pre_build:
        commands:
            - $(aws ecr get-login --no-invlude-email --region us-east-2)
    build:
        commands:
            - docker build -t myappdoc:latest .
            - docker tag myappdoc:latest 374849911922.dkr.ecr.us-east-2.amazonaws.com/myapprepo:latest
    post_build:
        commands:
            - docker push 374849911922.dkr.ecr.us-east-2.amazonaws.com/myapprepo:latest
            - printf '[{"name":myapptask,"imageUri":"%s"}]' 374849911922.dkr.ecr.us-east-2.amazonaws.com/myapprepo:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json